server:
  port: 8801

spring:
  application:
    name: ip-proxy
  profiles:
    active: dev

  data:
    mongodb:
      auto-index-creation: true # 是否允许自动创建索引

# 如果要在访问静态资源时，强制添加 static前缀
#  mvc:
#    static-path-pattern: /static/**
#    resources:
#      chain:
#        strategy:
#          content:
#            enabled: true
#            paths: /**

---  # 2个三横杠之间表示一个环境配置
spring:
  profiles: unittest # 单元测试，通过注解 ActiveProfiles 使用这一段
  # 注：连接信息直接写在test代码里，这里就不用配置了。

---
spring:
  profiles: dev # 开发使用这一段
  data:
    mongodb:
      host: 10.2.3.250
      port: 27017
      username: beinet
      password: beinet123
      database: firstdemo
---
